### ISSUE TITLE
Prefix dictionaries with the system

### ISSUE THREAD

**Issue by nsmarkop** [morinted/plover_palantype#2]
I was told this for my Korean system, but if you don't prefix your included dictionaries here with the system in some way then they could overwrite / re-use the ones for other systems. In the case of this system it seems that re-using the user.json of the default English stenotype is happening if it hasn't been moved from the configuration folder.

Perhaps the long term solution for this is to have a folder for each system (or plugin in general) in the configuration folder, but that's more of a topic for the main Plover repo maybe.

**Comment by panathea** [comment]
Thanks for the suggestion!
